### PR TITLE
Input router modification

### PR DESCRIPTION
**Pull request by sseifeln**
I've modified the input router algorithm to use the modified memory template; it still doesn't do anything with the stubs though!

### CODE REVIEW

**Comment by pwittich** [comment]
It looks like the entire input router was commented out in this PR. Is there a good reason to submit this now rather than waiting until the IR actually does something?

**Comment by sseifeln** [comment]
Nope .. especially since I just noticed that this was a total git fail (the changes I *did* make are not in the commit). I'm going to close the request and try again later - when it works and when I actually commit my changes! Sorry about that.

**Comment by pwittich** [comment]
you can just add new commits to the PR when you have them -- no need to close this PR!
thanks

**Comment by pwittich** [comment]
superseded by #72

**Pull request closed without merging**
