### PR TITLE
TrackletEngine update

### PR DESCRIPTION
**Pull request by ksung25**
TrackletEngine class is templated to be able to handle processing of any seeding and phi region. Complete set of cut tables are added to emData/TE directory. The module passes cosimulation.

### CODE REVIEW

**Comment by pwittich** [comment]
I was not expecting to see 1600 files changed?

**Comment by pwittich** [comment]
right now I think the emData/TE has very few files in it, maybe we don't want to have all the data files in github?

**Comment by ksung25** [comment]
Shall I make a new pull request with all the emData/TE files removed (except the one that works with the test bench)? I can host these data files on some public space for now.

**Comment by ksung25** [comment]
Data files removed and pushed to this PR

**Pull request merged**
