### PR TITLE
Pr arrays

### PR DESCRIPTION
**Pull request by djcranshaw**
Change to using arrays of memory classes for inputs and outputs of Projection Router rather than individual pointers. In addition to simplifying the code on the interface (the synthesized interface is unchanged except port names), the logic for reading the input memories has been fairly substantially simplified which resulted in the new PR using about 60% of the resources of the old PR (FF and LUTs, mainly).

### CODE REVIEW

**Comment by pwittich** [comment]
Sounds great! can you point to the changes that reduced the resource usage so dramatically? I can't really tell from looking at the 'files changed' tab.

**Comment by djcranshaw** [comment]
> Sounds great! can you point to the changes that reduced the resource usage so dramatically? I can't really tell from looking at the 'files changed' tab.

So I did some digging and found out that about half of the improvement comes from removing all of the recursive function calls in lines 14-71 of ProjectionRouter.h https://github.com/cms-tracklet/firmware-hls/blob/9d1b291bd67150495319e6139f963a8044b82c33/TrackletAlgorithm/ProjectionRouter.h#L16-L70

**Comment by djcranshaw** [comment]
> Sounds great! can you point to the changes that reduced the resource usage so dramatically? I can't really tell from looking at the 'files changed' tab.

So I did some digging and found that about half of the improvement comes from removing the recursive functions calls from lines 14-71 in ProjectionRouter.h. I'm not exactly sure what causes the improvement (or rather what about those function calls causes the extra usage) but getting rid of them is what's responsible for about half of the reduction in resources. The other half comes from changing the ints in nvmprojout (lines 217-225) to ap_uint<7>. I was surprised by this because I thought HLS was suppose to figure out how big these internal ints need to be and adjust their size accordingly, but maybe it can't figure out enough about the internal logic of the PR to make that determination.

**Comment by pwittich** [comment]
Ah, removing recursion is a good one. And the `ap_uint<X>` is also a good thing to know...

**Comment by pwittich** [comment]
I'm confused, the commit appears as coming from someone I don't know? @aehart ?
image

**Comment by aehart** [comment]
> I'm confused, the commit appears as coming from someone I don't know? @aehart ?
> image

My bad. I pushed from a shared machine where somebody decided to set up the gitconfig with their name. I just fixed it.

**Comment by pwittich** [comment]
> > I'm confused, the commit appears as coming from someone I don't know? @aehart ?
> > image
> 
> My bad. I pushed from a shared machine where somebody decided to set up the gitconfig with their name. I just fixed it.

mystery solved!

**Pull request merged**
